import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms and Conditions - CareerPilotAI",
  description: "Terms and Conditions for CareerPilotAI - Learn about our service terms, user responsibilities, and legal agreements.",
}

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="prose prose-gray dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
          
          <p className="text-lg text-muted-foreground mb-8">
            <strong>Effective Date:</strong> {new Date().toLocaleDateString('en-IN', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using CareerPilotAI ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">2. Service Description</h2>
            <p className="mb-4">
              CareerPilotAI is an AI-powered platform that provides:
            </p>
            <ul className="list-disc pl-6">
              <li>Resume generation and optimization services</li>
              <li>Cover letter creation tools</li>
              <li>LinkedIn bio generation</li>
              <li>Document export in multiple formats (PDF, DOCX, TXT)</li>
              <li>Subscription-based premium features</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">3. User Accounts and Registration</h2>
            <h3 className="text-xl font-medium mb-3">3.1 Account Creation</h3>
            <p className="mb-4">
              To use our services, you must create an account by providing accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials.
            </p>
            
            <h3 className="text-xl font-medium mb-3">3.2 Account Responsibilities</h3>
            <ul className="list-disc pl-6">
              <li>You must be at least 18 years old to use our services</li>
              <li>Provide accurate and truthful information</li>
              <li>Maintain the security of your account</li>
              <li>Notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">4. Subscription Plans and Payments</h2>
            <h3 className="text-xl font-medium mb-3">4.1 Plan Types</h3>
            <ul className="list-disc pl-6 mb-4">
              <li><strong>Free Plan:</strong> Limited access to basic features</li>
              <li><strong>Basic Plan:</strong> ₹499 - Enhanced features with usage limits</li>
              <li><strong>Premium Plan:</strong> ₹999 - Unlimited access to all features</li>
            </ul>

            <h3 className="text-xl font-medium mb-3">4.2 Payment Terms</h3>
            <ul className="list-disc pl-6">
              <li>All payments are processed securely through Razorpay</li>
              <li>Subscription fees are charged in advance</li>
              <li>Prices are subject to change with 30 days notice</li>
              <li>All fees are non-refundable except as stated in our refund policy</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">5. User Content and Intellectual Property</h2>
            <h3 className="text-xl font-medium mb-3">5.1 Your Content</h3>
            <p className="mb-4">
              You retain ownership of all content you provide to our service. By using our service, you grant us a license to use your content solely for providing our services.
            </p>

            <h3 className="text-xl font-medium mb-3">5.2 Generated Content</h3>
            <p className="mb-4">
              Content generated by our AI tools belongs to you. However, you acknowledge that similar content may be generated for other users.
            </p>

            <h3 className="text-xl font-medium mb-3">5.3 Our Intellectual Property</h3>
            <p>
              The CareerPilotAI platform, including its design, functionality, and underlying technology, is our intellectual property and is protected by copyright and other laws.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Prohibited Uses</h2>
            <p className="mb-4">You agree not to use the service to:</p>
            <ul className="list-disc pl-6">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Upload malicious code or attempt to hack the system</li>
              <li>Create false or misleading content</li>
              <li>Resell or redistribute our services without permission</li>
              <li>Use the service for any illegal or unauthorized purpose</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. Service Availability and Modifications</h2>
            <p>
              We strive to maintain high service availability but do not guarantee uninterrupted access. We reserve the right to modify, suspend, or discontinue any part of our service with reasonable notice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, CareerPilotAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or other intangible losses.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold CareerPilotAI harmless from any claims, damages, or expenses arising from your use of the service or violation of these terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
            <p className="mb-4">
              Either party may terminate this agreement at any time. Upon termination:
            </p>
            <ul className="list-disc pl-6">
              <li>Your access to the service will be suspended</li>
              <li>You may download your data within 30 days</li>
              <li>We may delete your account and data after the grace period</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through our platform. Continued use of the service constitutes acceptance of the modified terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">13. Contact Information</h2>
            <p className="mb-4">
              For questions about these Terms and Conditions, please contact us:
            </p>
            <div className="bg-muted p-4 rounded-lg">
              <p><strong>Email:</strong> legal@careerpilotai.com</p>
              <p><strong>Address:</strong> CareerPilotAI, India</p>
              <p><strong>Phone:</strong> +91-XXXXXXXXXX</p>
            </div>
          </section>

          <div className="border-t pt-8 mt-8">
            <p className="text-sm text-muted-foreground">
              These Terms and Conditions were last updated on {new Date().toLocaleDateString('en-IN', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}. 
              By using CareerPilotAI, you acknowledge that you have read and agreed to these terms.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
